# Generated by Django 5.1.3 on 2024-11-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=10, max_digits=20)),
                ('locked', models.DecimalField(decimal_places=10, max_digits=20)),
                ('avg_buy_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('avg_buy_price_modified', models.BooleanField()),
                ('unit_currency', models.CharField(max_length=10)),
            ],
        ),
    ]
