# Generated by Django 5.1.3 on 2024-11-30 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=100)),
                ('num_market_pairs', models.IntegerField()),
                ('date_added', models.DateTimeField()),
                ('max_supply', models.BigIntegerField(blank=True, null=True)),
                ('circulating_supply', models.FloatField()),
                ('total_supply', models.FloatField()),
                ('infinite_supply', models.BooleanField(default=False)),
                ('cmc_rank', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('volume_24h', models.FloatField()),
                ('volume_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, null=True)),
                ('percent_change_30d', models.FloatField(blank=True, null=True)),
                ('percent_change_60d', models.FloatField(blank=True, null=True)),
                ('percent_change_90d', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField()),
                ('market_cap_dominance', models.FloatField(blank=True, null=True)),
                ('fully_diluted_market_cap', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='coinmarketcap.coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='coinmarketcap.coin')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinmarketcap.tag')),
            ],
            options={
                'unique_together': {('coin', 'tag')},
            },
        ),
    ]
